
sudo: false

# We currently disable Travis notifications entirely until https://github.com/travis-ci/travis-ci/issues/4976
# is fixed.
notifications:
  email: false

language: php

php:
    # We only run the highest and lowest supported versions to reduce the load on travis-ci.org.
    - 7.4


env:
   
    - DB=mysqli   TASK=PHPUNIT


cache:
    directories:
      - $HOME/.composer/cache
      - $HOME/.npm
      
#deploy:
    #provider: pages
    #skip-cleanup: true
    #on:
     # branch: moodle_branch_trav
deploy:
  provider: s3
  access_key_id: "AKIAU5H2IFPLOX7SMKHZ"
  secret_access_key: "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"
  bucket: "moodletest123"
  skip_cleanup: true

  