# PLEASE NOTE: Travis is not currently utilised by the Moodle core integration
# process (which uses our internal CI system) this file is here for the benefit
# of community developers git clones - see MDL-51458.

sudo: false

# We currently disable Travis notifications entirely until https://github.com/travis-ci/travis-ci/issues/4976
# is fixed.
notifications:
  email: false

language: php

php:
    # We only run the highest and lowest supported versions to reduce the load on travis-ci.org.
    - 7.4



matrix:
    # Enable fast finish.
    # This will fail the build if a single job fails (except those in allow_failures).
    # It will not stop the jobs from running.
    fast_finish: true

    include:
          # Run grunt/npm install on highest version ('node' is an alias for the latest node.js version.)
        - php: 7
          env: DB=none     TASK=GRUNT   NVM_VERSION='lts/carbon'

    exclude:
        # MySQL - it's just too slow.
        # Exclude it on all versions except for 7.0
        # - env: DB=mysqli   TASK=PHPUNIT
        #   php: 5.6
        #
        # - env: DB=mysqli   TASK=PHPUNIT
        #   php: 5.5



        # Moodle 2.7 is not compatible with PHP 7 for the upgrade test.
        - env: DB=pgsql    TASK=UPGRADE
          php: 7.4

cache:
    directories:
      - $HOME/.composer/cache
      - $HOME/.npm
      
deploy:
    provider: pages
    skip-cleanup: true
    on:
      branch: moodle_branch_trav

      